### ISSUE TITLE
Add Clone trait implementation to Lang enum

### ISSUE THREAD

**Issue by minetake01** [Avimitin/deepl-rs#13]
Hi,

I'm currently using the deepl-rs crate and I found it difficult to work with the Lang enum. It currently does not implement the Clone trait, which makes it cumbersome to use in certain scenarios.

I believe that adding the Clone trait implementation to the Lang enum would make it much easier to work with. Is there any reason why the trait was not implemented in the first place? If there are no concerns or objections, would it be possible to add the Clone trait implementation to the Lang enum?

Thank you for your time and consideration.

**Comment by Avimitin** [comment]
Sry I just forgot to add that derive. It should be fixed now :)

**Comment by minetake01** [comment]
Thank you for your prompt response. I'm glad to hear that the issue will be fixed in v0.4.1. I appreciate your effort in resolving this issue.

Looking forward to using the updated version. Thank you again for your support.
