### ISSUE TITLE
Api endpoint /document

### ISSUE THREAD

**Issue by Ganneff** [Avimitin/deepl-rs#2]
Hi

wishlist, the /document part of the deepl api should be supported.

Greetings,
  Ganneff

**Comment by Avimitin** [comment]
There are much IO functionality should be implemented, it needs some time to complete.

**Comment by Ganneff** [comment]
Wow, that was fast.
Thank you, makes my task much easier now!

**Comment by Avimitin** [comment]
> Wow, that was fast. Thank you, makes my task much easier now!

The test is simple so there might be some corner case causing bugges, feel free to open new issue :)
