### ISSUE TITLE
Glossarie Support

### ISSUE THREAD

**Issue by turulix** [Avimitin/deepl-rs#21]
Hey it would be amazing if this library could have a basic implementation for the Glossaries Api :)
https://www.deepl.com/de/docs-api/glossaries

**Comment by Avimitin** [comment]
Glossary APIs have CRUD and list operations, it takes time to implement these APIs in Rust. Because I don't have that much free time, so it might take longer than you expected to finish. But anyway, the create glossary API is already implemented in commit d1ae77f1f11582f1c67e8662389ff87a6bca0ecf. You can take a look at it and see if you like this API design in Rust.

**Comment by Avimitin** [comment]
> I'm trying to add multiple entires

This is how DeepL design their API. They don't provide API to batch update glossaries.

I can add another helper function for this, but all I can do is make this action more comfortable. It still require multiple http requests.

**Comment by turulix** [comment]
The way i understood the API is that once a glossary is created, it basically becomes unmutable. For my application, it is totally fine to create a glossary with all the required entries and then just delete it once it is finished being used

**Comment by Avimitin** [comment]
> it basically becomes immutable

No it isn't. You can call the delete glossary API. All CRUD operation are supported. What I meant is that the DeepL official APIs doesn't support batch glossary update, so this Rust wrapper doesn't consider batch update at design stage.

**Comment by turulix** [comment]
> > it basically becomes immutable
> 
> No it isn't. You can call the delete glossary API. All CRUD operation are supported. What I meant is that the DeepL official APIs doesn't support batch glossary update, so this Rust wrapper doesn't consider batch update at design stage.
> 
> Here is the CRUD operation example https://github.com/Avimitin/deepl-rs/blob/b625f1ec565ab507a1566d19e4ecd6e55e1205c7/src/endpoint/glossary.rs#L219.

![Screenshot_20240227_151727_Brave.jpg](https://github.com/Avimitin/deepl-rs/assets/28957605/de61e814-9eeb-4a38-8f4a-8e694d9cfe34)

**Comment by Avimitin** [comment]
I do a final check on formats and finally know what you mean. https://www.deepl.com/de/docs-api/glossaries/formats

**Comment by Avimitin** [comment]
Should be fixed in [v0.6.0](https://github.com/Avimitin/deepl-rs/releases/tag/v0.6.0).
