### ISSUE TITLE
Make Fields in Glossaries public

### ISSUE THREAD

**Issue by turulix** [Avimitin/deepl-rs#23]
I would love to be able to access these fields to be able to wrap them for my API :). https://github.com/Avimitin/deepl-rs/blob/67bb917909f921173bc3a7bd47986bfc932f7660/src/endpoint/glossary.rs#L115-L118

Also: https://github.com/Avimitin/deepl-rs/blob/67bb917909f921173bc3a7bd47986bfc932f7660/src/endpoint/glossary.rs#L56-L73

**Comment by Avimitin** [comment]
Oops...I forgot to make them public. Emmm I think I need to add some smoke tests outside of the crate.

**Comment by turulix** [comment]
No worries, made a PR to fix it ^^
