### ISSUE TITLE
Language details for en/pt

### ISSUE THREAD

**Issue by Ganneff** [Avimitin/deepl-rs#3]
https://github.com/Avimitin/deepl-rs/blob/abad6da3c98136ba28975fd25279cc595d068a4b/src/lib.rs#L67-L106

The current Deepl API doc says, that translation target language english should select en-GB or en-US, portuguese should select pt-BR or pt-PT, this here does not allow this.

Greetings,
  Ganneff

**Comment by Avimitin** [comment]
I will take a deeper investigation tomorrow. Sry for the lack of functionality.

**Comment by Ganneff** [comment]
> I will take a deeper investigation tomorrow. Sry for the lack of functionality.

Thanks.
And no reason to be sorry. You wrote something I can use. It's just not finished yet, that's all OK.
