### ISSUE TITLE
Idiomatic FromStr implementation for Lang

### ISSUE THREAD

**Issue by tmpfs** [Avimitin/deepl-rs#30]
Hi,

I have been evaluating this library and looking at the code and was surprised to see you implemented `TryFrom` for `Lang` rather than implementing `Display` and `FromStr`.

If `FromStr` is implemented then we could call `parse()?` and the `Lang` type could easily be used with tools like `clap` for command line apps.

It would be pretty straightforward to just wrap `TryFrom` for now but I think it would be cleaner to just implement `FromStr` - what do you think?

Cheers!

**Comment by Avimitin** [comment]
Thank you for bringing this to my attention! I've totally forgot the FromStr trait. I would like to fix this in next release, but I'm currently swamped with work. If you're interested in fixing this in new PR, I'd be extremely grateful for any help you can offer.

**Comment by Avimitin** [comment]
These trait should be now available since v0.6.3.
