### ISSUE TITLE
PathBuf, not str

### ISSUE THREAD

**Issue by Ganneff** [Avimitin/deepl-rs#5]
Hi

this code:

https://github.com/Avimitin/deepl-rs/blob/f630c4a6739179fca576cd70414d086054f48243/src/lib.rs#L114

means that I have to give file_path as string. And can't use the PathBuf I already have, because - well, I am dealing with a filename here. So I would need to convert to string, just so that the thing converts it back. Would probably be nicer to directly take PathBuf.

Greetings
 Ganneff

**Comment by Avimitin** [comment]
Oops, I will rewrite it to take generic.
