### ISSUE TITLE
Downloaded document broken

### ISSUE THREAD

**Issue by Ganneff** [Avimitin/deepl-rs#6]
Hi,

I tried translating a document using the new upload functionality. It appears to work, except - the downloaded file is truncated in some way.
Upload is 54784bytes of a word .docx file witha bunch of pages of text and a table.
Download is always below 4k in size.

Using curl directly with the same file it translates nicely and gets me the full one back, so its not the file breaking DeepL, but somewhere in rust.

Sorry, I can't point to anything directly right now, just copied your code (and adjusted variable names) and run with it... Maybe you can successfully reproduce?

Greetings
  Ganneff

**Comment by Avimitin** [comment]
Do you have the content of the downloaded file?

**Comment by Ganneff** [comment]
It is actually a zip file that (if you look with less) starts with PK, then some "garbage", then "docProps/core.xml" and later docProps/app.xml and word/document.xml, so I doubt the error response. Pretty similar to the looks of a regular file.

The part of the code around this is:

```rust
                let ffile = working.to_str().unwrap();
                let upload_file = UploadDocumentProp::builder()
                    .target_lang(target)
                    .file_path(&ffile)
                    .build();
                let response = api.upload_document(upload_file).await?;
                let mut status = api.check_document_status(&response).await?;
                loop {
                    if status.status.is_done() {
                        info!(
                            "Document {}, Billed Characters: {}",
                            ffile,
                            status.billed_characters.unwrap()
                        );
                        break;
                    }
                    trace!(
                        "Need to wait more, it says: {}",
                        status.seconds_remaining.unwrap()
                    );
                    if let Some(msg) = status.error_message {
                        return Err(anyhow!("Translation failed: {}", msg));
                    }
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    status = api.check_document_status(&response).await?;
                }
                // After translation done, download it
                let path = api
                    .download_document(&response, "translated.docx", None)
                    .await?;
```

**Comment by Avimitin** [comment]
I am really stupid. I overwrite a part of the response over and over again into the same position of the file. I don't test it out because my test data is small enough to write into file at once. But for large file, the later bytes will overwrite the bytes before.

**Comment by Avimitin** [comment]
My character limit exceed... This issue might be fixed, but I can't test it now.

**Comment by Ganneff** [comment]
This issue is fixed in your fix-download branch, I just set it up to test. That is, I cloned your repo and used deepl-rs using path= in Cargo.toml, rebuild (it got some new toki-stream/syn/tokio-macros libs) and tried with the same file yesterday after adjusting my code for the PathBuf input.

I do have to fix the output name on my side, but the translated and downloaded file now works flawlessly, so IMO you can merge this and release.

THANKS for this!

**Comment by Avimitin** [comment]
> This issue is fixed in your fix-download branch, I just set it up to test. That is, I cloned your repo and used deepl-rs using path= in Cargo.toml, rebuild (it got some new toki-stream/syn/tokio-macros libs) and tried with the same file yesterday after adjusting my code for the PathBuf input.
> 
> I do have to fix the output name on my side, but the translated and downloaded file now works flawlessly, so IMO you can merge this and release.
> 
> THANKS for this!

Can you successfully open the downloaded file? I am worry about if it is working or not...

**Comment by Ganneff** [comment]
I did, yes. Tried with two files, thats the "now works flawlessly".

**Comment by Avimitin** [comment]
Great! I will merge and release new version now.
