### ISSUE TITLE
Should use PathBuf?

### ISSUE THREAD

**Issue by Ganneff** [Avimitin/deepl-rs#9]
https://github.com/Avimitin/deepl-rs/blob/a0ef733a282f7dcd0d537cdc0a4c37cf2e2e96dc/src/lib.rs#L524

Same as with input file, should this also use/accept PathBuf here?
*IMO* yes.

You join it into a PathBuf around line 551. If you just let user provide PathBuf, you could also drop the output_dir parameter (which is also just str :) ) and require the PathBuf to be the full directory + filename.

Greetings
  Ganneff

**Comment by Avimitin** [comment]
Yes I am currently rewriting this, also some non-copy optimization, please wait, it won't take too much time.

**Comment by Avimitin** [comment]
Please confirm that the issue is actually fixed. My account characters limit will be refreshed after Dec 18. I can't test anything right now :(

**Comment by Ganneff** [comment]
Works nicely, thanks. I translated things to random languages and it works. Using the 0.1.6 release, so including the latest changes here.
I'm at 80% of the 500k character limit right now. Damn 50k per file they take, even if its smaller.
